### ISSUE TITLE
wireguard cannot work by docker

### ISSUE THREAD

**Issue by frui85** [jippi/docker-pritunl#27]
![image](https://user-images.githubusercontent.com/10277372/221776793-215fbf32-9362-43a7-90e6-5c0b4cf48e6b.png)

logs:

[patient-thunder-4691][2023-02-28 14:42:05,478][ERROR] Failed to check notifications
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/runners/updates.py", line 25, in _check_updates
    response = urllib.request.urlopen(request, timeout=60)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
[patient-thunder-4691][2023-02-28 14:42:05,484][WARNING] Failed to get public ip address
[patient-thunder-4691][2023-02-28 14:42:05,703][INFO] Starting server
  selinux_context = "none"
[patient-thunder-4691][2023-02-28 14:42:05,703][INFO] Generating server certificate...
[patient-thunder-4691][2023-02-28 14:42:07,222][INFO] Retrying get public ip address
[patient-thunder-4691][2023-02-28 14:42:10,227][INFO] Retrying get public ip address
[patient-thunder-4691][2023-02-28 14:42:13,231][INFO] Retrying get public ip address
[patient-thunder-4691][2023-02-28 14:42:16,233][INFO] Retrying get public ip address
[patient-thunder-4691][2023-02-28 14:42:16,235][WARNING] Failed to get public ip address
[patient-thunder-4691][2023-02-28 14:44:41,007][INFO] Starting vpn server
  server_id        = "63fda2cd63b1bd184972bd12"
  instance_id      = "63fda2d963b1bd184972bd27"
  instances        = []
  instances_count  = 0
  route_count      = 1
  network          = "10.8.0.0/24"
  network6         = "fd00:a080::/64"
  dynamic_firewall = false
  host_id          = "add784af049f44bc9a79768b56049f0b"
  host_address     = "192.168.0.10"
  host_address6    = "fe80::c9e5:d139:ca9f:7b83"
  host_networks    = ["192.168.0.0/22", "172.17.0.0/16"]
  cur_timestamp    = "2023-02-28 06:44:41.007481"
  libipt           = false
[patient-thunder-4691][2023-02-28 14:44:41,594][ERROR] Failed to add wg interface
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1306, in start_wg
    utils.check_output_logged([
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/utils/misc.py", line 223, in check_output_logged
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ip', 'link', 'add', 'dev', 'wg0', 'type', 'wireguard']' returned non-zero exit status 2.
  server_id = "63fda2cd63b1bd184972bd12"
[patient-thunder-4691][2023-02-28 14:44:41,595][ERROR] Popen returned error exit code
  cmd         = ["ip", "link", "add", "dev", "wg0", "type", "wireguard"]
  return_code = 2
Process stderr:
  RTNETLINK answers: Operation not supported
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1650, in _run_thread
    self.start_wg()
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1306, in start_wg
    utils.check_output_logged([
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/utils/misc.py", line 216, in check_output_logged
    logger.error('Popen returned error exit code', 'utils',
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[patient-thunder-4691][2023-02-28 14:44:41,613][ERROR] Server error occurred while running
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1650, in _run_thread
    self.start_wg()
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1306, in start_wg
    utils.check_output_logged([
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/utils/misc.py", line 223, in check_output_logged
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ip', 'link', 'add', 'dev', 'wg0', 'type', 'wireguard']' returned non-zero exit status 2.
  server_id   = "63fda2cd63b1bd184972bd12"
  instance_id = "63fda2d963b1bd184972bd27"
[patient-thunder-4691][2023-02-28 14:44:41,984][ERROR] Failed to stop wg interface
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1385, in stop_wg
    utils.check_output_logged([
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/utils/misc.py", line 223, in check_output_logged
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ip', 'link', 'set', 'wg0', 'down']' returned non-zero exit status 1.
  server_id = "63fda2cd63b1bd184972bd12"
[patient-thunder-4691][2023-02-28 14:44:41,985][ERROR] Popen returned error exit code
  cmd         = ["ip", "link", "set", "wg0", "down"]
  return_code = 1
Process stderr:
  Cannot find device "wg0"
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1831, in _run_thread
    self.stop_wg()
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1385, in stop_wg
    utils.check_output_logged([
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/utils/misc.py", line 216, in check_output_logged
    logger.error('Popen returned error exit code', 'utils',
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[patient-thunder-4691][2023-02-28 14:44:42,000][ERROR] Failed to del wg interface
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1395, in stop_wg
    utils.check_output_logged([
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/utils/misc.py", line 223, in check_output_logged
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ip', 'link', 'del', 'dev', 'wg0']' returned non-zero exit status 1.
  server_id = "63fda2cd63b1bd184972bd12"
[patient-thunder-4691][2023-02-28 14:44:42,001][ERROR] Popen returned error exit code
  cmd         = ["ip", "link", "del", "dev", "wg0"]
  return_code = 1
Process stderr:
  Cannot find device "wg0"
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1831, in _run_thread
    self.stop_wg()
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1395, in stop_wg
    utils.check_output_logged([
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/utils/misc.py", line 216, in check_output_logged
    logger.error('Popen returned error exit code', 'utils',
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[patient-thunder-4691][2023-02-28 14:45:00,592][INFO] Starting vpn server
  server_id        = "63fda2cd63b1bd184972bd12"
  instance_id      = "63fda2ec63b1bd184972bd44"
  instances        = []
  instances_count  = 0
  route_count      = 1
  network          = "10.8.0.0/24"
  network6         = "fd00:a080::/64"
  dynamic_firewall = false
  host_id          = "add784af049f44bc9a79768b56049f0b"
  host_address     = "192.168.0.10"
  host_address6    = "fe80::c9e5:d139:ca9f:7b83"
  host_networks    = ["192.168.0.0/22", "172.17.0.0/16"]
  cur_timestamp    = "2023-02-28 06:45:00.591786"
  libipt           = false
[patient-thunder-4691][2023-02-28 14:45:01,210][ERROR] Failed to add wg interface
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1306, in start_wg
    utils.check_output_logged([
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/utils/misc.py", line 223, in check_output_logged
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ip', 'link', 'add', 'dev', 'wg1', 'type', 'wireguard']' returned non-zero exit status 2.
  server_id = "63fda2cd63b1bd184972bd12"
[patient-thunder-4691][2023-02-28 14:45:01,211][ERROR] Popen returned error exit code
  cmd         = ["ip", "link", "add", "dev", "wg1", "type", "wireguard"]
  return_code = 2
Process stderr:
  RTNETLINK answers: Operation not supported
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1650, in _run_thread
    self.start_wg()
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/server/instance.py", line 1306, in start_wg
    utils.check_output_logged([
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/utils/misc.py", line 216, in check_output_logged
    logger.error('Popen returned error exit code', 'utils',
  File "/usr/lib/pritunl/lib/python3.8/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()

**Comment by frui85** [comment]
![image](https://user-images.githubusercontent.com/10277372/221777034-9cba7cdc-253e-4310-a05e-d8e27a25cb5e.png)

**Comment by jippi** [comment]
can't reproduce :(
