### ISSUE TITLE
[ERROR] Popen returned error exit code

### ISSUE THREAD

**Issue by Fabricio872** [jippi/docker-pritunl#28]
Hello, I am getting this error after i have upgraded to image a9aa1d2a63efc7f58340d78547086b7fd1a1c445b09b0d3fa772276f2465a8e7 since upgrade i could not make pritunl work i have tried delete my volumes and pull the image but i have ended up with same results. i am running Alpine Linux v3.18 with kernel 6.1.32-0-lts docker version 24.0.2 and docker compose v2.18.1. the whole error looks like this:

```logs
[undefined][2023-06-12 09:34:20,858][INFO] Starting setup server
[undefined][2023-06-12 09:34:20,875][INFO] Generating setup server ssl cert
[ancient-plateau-4428][2023-06-12 09:34:26,484][INFO] Starting server
  selinux_context = "none"
[ancient-plateau-4428][2023-06-12 09:34:26,485][INFO] Generating server certificate...
[ancient-plateau-4428][2023-06-12 09:37:39,803][INFO] Starting vpn server
  server_id        = "6486e75b41761be5a0330eaf"
  instance_id      = "6486e76341761be5a0330ebf"
  instances        = []
  instances_count  = 0
  route_count      = 1
  network          = "192.168.237.0/24"
  network6         = "fd00:c0a8:ed00::/64"
  dynamic_firewall = false
  host_id          = "4e1aa29eab8b497eaa243f66b02f7e35"
  host_address     = "192.168.48.2"
  host_address6    = null
  host_networks    = ["192.168.48.0/20"]
  cur_timestamp    = "2023-06-12 09:37:39.802316"
  libipt           = false
[ancient-plateau-4428][2023-06-12 09:37:40,683][ERROR] Popen returned error exit code
  cmd         = ["iptables", "-I", "INPUT", "-i", "tun0", "-j", "ACCEPT", "-m", "comment", "--comment", "pritunl-6486e75b41761be5a0330eaf"]
  timeout     = 15
  return_code = 3
Process stderr:
  modprobe: FATAL: Module ip_tables not found in directory /lib/modules/6.1.32-0-lts
  iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
  Perhaps iptables or your kernel needs to be upgraded.
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/server/instance.py", line 1582, in _run_thread
    self.iptables.upsert_rules()
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/iptables.py", line 1411, in upsert_rules
    self._insert_iptables_rule(rule, tables=tables)
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/iptables.py", line 1229, in _insert_iptables_rule
    return self._insert_iptables_rule_cmd(rule, ipv6)
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/iptables.py", line 1213, in _insert_iptables_rule_cmd
    ).run(15)
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/utils/proc.py", line 85, in run
    stderr=self._stderrdata,
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[ancient-plateau-4428][2023-06-12 09:37:40,686][ERROR] Failed to insert iptables rule, retrying...
  rule = ["INPUT", "-i", "tun0", "-j", "ACCEPT", "-m", "comment", "--comment", "pritunl-6486e75b41761be5a0330eaf"]
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/server/instance.py", line 1582, in _run_thread
    self.iptables.upsert_rules()
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/iptables.py", line 1411, in upsert_rules
    self._insert_iptables_rule(rule, tables=tables)
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/iptables.py", line 1229, in _insert_iptables_rule
    return self._insert_iptables_rule_cmd(rule, ipv6)
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/iptables.py", line 1221, in _insert_iptables_rule_cmd
    rule=rule,
  File "/usr/lib/pritunl/lib/python3.6/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[ancient-plateau-4428][2023-06-12 09:37:41,216][ERROR] Popen returned error exit code
  cmd         = ["iptables", "-I", "INPUT", "-i", "tun0", "-j", "ACCEPT", "-m", "comment", "--comment", "pritunl-6486e75b41761be5a0330eaf"]
  timeout     = 15
  return_code = 3
```
and then it is stuck in a loop

my docker compose file looks like this:
```docker-compose
version: '3.4'
services:
  pritunl:
    container_name: pritunl
    image: ghcr.io/jippi/docker-pritunl
    restart: unless-stopped
    privileged: true
    ports:
      - '420:443'
      - '1194:1194'
      - '1194:1194/udp'
    dns:
      - 1.1.1.1
    volumes:
      - 'conf:/etc/'
      - 'data:/var/lib/pritunl'
      - 'db:/var/lib/mongodb'

volumes:
  conf:
  data:
  db:
```

please help i can provide additional related information just ask.

**Comment by jippi** [comment]
Hmm, not entirely sure whats up with that error

```
  iptables v1.6.1: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
  Perhaps iptables or your kernel needs to be upgraded.
``` 

seems to be the problem, which is likely a host (outside of Docker) issue - maybe you need to load the "iptables filter" kernel module?

**Comment by Fabricio872** [comment]
oh thank you i was able to resolve the issue by executing these commands to add required kernel modules
```
modprobe ip_tables
rc-update add iptables
rc-update add ip6tables
```
but they were not configured yet so they didn't start on boot and complain they didn't have a configuration. this I have resolved by enabling firewall (ufw in my case) and then disabling it since I don't use it on my local network. after that pritunl is starting correctly.
